#!/usr/bin/env bash

# 📋 COMANDOS RÁPIDOS - Copia y pega

echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║                     QUICK COMMANDS                            ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""

# DEVELOPMENT
echo "🖥️  DEVELOPMENT"
echo "─────────────────────────────────────────"
echo ""
echo "Start development server:"
echo "  npm run dev"
echo ""
echo "Build for production:"
echo "  npm run build"
echo ""
echo "Run production build:"
echo "  npm start"
echo ""

# DATABASE
echo "🗄️  DATABASE"
echo "─────────────────────────────────────────"
echo ""
echo "Open Prisma Studio UI:"
echo "  npx prisma studio"
echo ""
echo "Regenerate Prisma Client:"
echo "  npx prisma generate"
echo ""
echo "Sync schema with MongoDB:"
echo "  npx prisma db push"
echo ""

# DEPENDENCIES
echo "📦 DEPENDENCIES"
echo "─────────────────────────────────────────"
echo ""
echo "Install all packages:"
echo "  npm install"
echo ""
echo "Install specific package:"
echo "  npm install package-name"
echo ""
echo "Update packages:"
echo "  npm update"
echo ""

# CODE QUALITY
echo "✨ CODE QUALITY"
echo "─────────────────────────────────────────"
echo ""
echo "Run linter:"
echo "  npm run lint"
echo ""
echo "Check TypeScript:"
echo "  npx tsc --noEmit"
echo ""

# ENVIRONMENT
echo "⚙️  ENVIRONMENT SETUP"
echo "─────────────────────────────────────────"
echo ""
echo "Generate NEXTAUTH_SECRET:"
echo "  openssl rand -base64 32"
echo ""
echo "Or use Node:"
echo "  node -e \"console.log(require('crypto').randomBytes(32).toString('base64'))\""
echo ""

# USEFUL URLs
echo "🌐 URLS"
echo "─────────────────────────────────────────"
echo ""
echo "Local development:"
echo "  http://localhost:3000"
echo ""
echo "Login page:"
echo "  http://localhost:3000/login"
echo ""
echo "Forgotten password:"
echo "  http://localhost:3000/forgot-password"
echo ""
echo "Prisma Studio:"
echo "  http://localhost:5555"
echo ""

# ENV FILE TEMPLATE
echo "📄 .env.local TEMPLATE"
echo "─────────────────────────────────────────"
echo ""
echo "Copy and paste this into your .env.local:"
echo ""
echo "DATABASE_URL=\"mongodb+srv://username:password@host/nanPageDatabase\""
echo "NEXTAUTH_SECRET=\"your-secret-from-openssl-command\""
echo "NEXTAUTH_URL=\"http://localhost:3000\""
echo "EMAIL_USER=\"your-email@gmail.com\""
echo "EMAIL_PASSWORD=\"your-app-password\""
echo ""

# TROUBLESHOOTING
echo "🔧 TROUBLESHOOTING"
echo "─────────────────────────────────────────"
echo ""
echo "Clear Next.js cache:"
echo "  rm -rf .next"
echo ""
echo "Reinstall dependencies:"
echo "  rm -rf node_modules"
echo "  npm install"
echo ""
echo "Reset everything:"
echo "  rm -rf .next node_modules"
echo "  npm install"
echo "  npm run build"
echo ""

# PORTS
echo "🔌 CHECK PORTS"
echo "─────────────────────────────────────────"
echo ""
echo "Check if port 3000 is in use (macOS/Linux):"
echo "  lsof -i :3000"
echo ""
echo "Kill process on port 3000 (macOS/Linux):"
echo "  kill -9 <PID>"
echo ""
echo "Check if port 3000 is in use (Windows):"
echo "  netstat -ano | findstr :3000"
echo ""
echo "Kill process on port 3000 (Windows):"
echo "  taskkill /PID <PID> /F"
echo ""

# USEFUL SCRIPTS
echo "🚀 USEFUL SCRIPTS"
echo "─────────────────────────────────────────"
echo ""
echo "Create new user via API (development):"
echo ""
echo "curl -X POST http://localhost:3000/api/auth/register \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d '{\"name\":\"Test User\",\"email\":\"test@example.com\",\"password\":\"TestPass123\"}'"
echo ""

# DOCUMENTATION
echo "📚 DOCUMENTATION"
echo "─────────────────────────────────────────"
echo ""
echo "Read in this order:"
echo ""
echo "1. START_HERE.md           (Now!)"
echo "2. QUICKSTART.md           (2 min)"
echo "3. SETUP_INSTRUCTIONS.md   (10 min)"
echo "4. FAQ.md                  (5 min)"
echo ""

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "✅ Copy any command above and run in terminal"
echo ""
